foreground           #decbb7
background           #1c1412

selection_foreground #1c1412
selection_background #a47551

color0 #1c1412
color1 #b85a4b
color2 #7a8c67
color3 #c99452
color4 #5f788a
color5 #9e6752
color6 #6e8c85
color7 #ebdcd0
color8 #402f2a
color9 #d47565
color10 #97ab82
color11 #e3ae6d
color12 #7ba0b8
color13 #ba816c
color14 #8cb0a7
color15 #fff3e8

cursor                #a47551
cursor_text_color     #1c1412
url_color             #c99452

cursor_trail 4
cursor_trail_decay 0.1 0.4
