$background = 0d0e12
$onBackground = e4e4f0
$surface = 0d0e12
$surfaceDim = 0d0e12
$surfaceBright = 2a2c34
$surfaceContainerLowest = 000000
$surfaceContainerLow = 121318
$surfaceContainer = 181920
$surfaceContainerHigh = 1e1f26
$surfaceContainerHighest = 23252e
$onSurface = e4e4f0
$surfaceVariant = 23252e
$onSurfaceVariant = a9aab5
$outline = 73757f
$outlineVariant = 464750
$inverseSurface = faf8fe
$inverseOnSurface = 54555a
$shadow = 000000
$scrim = 000000
$surfaceTint = bac5ee
$primary = bac5ee
$primaryDim = adb8e0
$onPrimary = 343f61
$primaryContainer = 465174
$onPrimaryContainer = dce2ff
$inversePrimary = 535e81
$primaryFixed = c8d3fd
$primaryFixedDim = bac5ee
$onPrimaryFixed = 2a3556
$onPrimaryFixedVariant = 465174
$secondary = c1c6dd
$secondaryDim = b3b8cf
$onSecondary = 3a4052
$secondaryContainer = 353b4d
$onSecondaryContainer = babed5
$secondaryFixed = dde1f9
$secondaryFixedDim = cfd3eb
$onSecondaryFixed = 393f51
$onSecondaryFixedVariant = 565b6f
$tertiary = f3deff
$tertiaryDim = e9cdfd
$onTertiary = 604b72
$tertiaryContainer = e9cdfd
$onTertiaryContainer = 574269
$tertiaryFixed = e9cdfd
$tertiaryFixedDim = dabfee
$onTertiaryFixed = 442f55
$onTertiaryFixedVariant = 614b73
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = 6b769b
$secondaryPaletteKeyColor = 71768b
$tertiaryPaletteKeyColor = 856e98
$neutralPaletteKeyColor = 76767b
$neutralVariantPaletteKeyColor = 757680
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 6b769b
$secondary_paletteKeyColor = 71768b
$tertiary_paletteKeyColor = 856e98
$neutral_paletteKeyColor = 76767b
$neutral_variant_paletteKeyColor = 757680
$term0 = 353434
$term1 = 957dff
$term2 = 44def5
$term3 = ffdcf2
$term4 = 90acd6
$term5 = a6a2ee
$term6 = 9bcefe
$term7 = e8d3de
$term8 = ac9fa9
$term9 = ae9bff
$term10 = 89ecff
$term11 = fff0f6
$term12 = b0c2db
$term13 = beb8f7
$term14 = bae0ff
$term15 = ffffff
$rosewater = f5eff9
$flamingo = e5dff4
$pink = dbd9ff
$mauve = b3bcff
$red = b2aaff
$maroon = bfb8f0
$peach = e0c2f9
$yellow = ffecf3
$green = c8e3ff
$teal = cde1ff
$sky = c8dcff
$sapphire = abc8ff
$blue = a3bbff
$lavender = bdcbff
$klink = 6286d0
$klinkSelection = 6286d0
$kvisited = 6d77dd
$kvisitedSelection = 6d77dd
$knegative = 8872ff
$knegativeSelection = 8872ff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 4ab0ff
$kpositiveSelection = 4ab0ff
$text = e4e4f0
$subtext1 = a9aab5
$subtext0 = 73757f
$overlay2 = 64666f
$overlay1 = 55575f
$overlay0 = 474950
$surface2 = 393b41
$surface1 = 2b2d32
$surface0 = 1c1d22
$base = 0d0e12
$mantle = 0d0e12
$crust = 0c0d11
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
