# =========================
# MONITOR
# =========================

monitor=eDP-1,1920x1080@120,0x0,1   #change this according to your monitor

#==========================
# TERMINAL
#==========================

$terminal = kitty

# =========================
# ENV (NVIDIA + Wayland)
# =========================
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = ELECTRON_OZONE_PLATFORM_HINT,auto   # helps Electron apps (e.g. Discord, VS Code) run on Wayland
env = QT_QPA_PLATFORM,wayland             # forces Qt apps onto Wayland properly
env = XCURSOR_THEME,Oxygen 18 White
env = XCURSOR_SIZE,24
env = LANG,en_IN.UTF-8

# =========================
# CURSOR (NVIDIA fix)
# =========================
cursor {
    no_hardware_cursors = true   # NVIDIA GPUs often glitch with hardware cursors on Wayland
}

# =========================
# General/Themes
# =========================

general {
    layout = dwindle
}

decoration {
    active_opacity = 1.0
    inactive_opacity = 0.7
}

source = ~/dotfiles/hypr/.config/hypr/looks.conf
source = ~/.config/hypr/themes/current.conf

# =========================
# INPUT
# =========================
input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = -0.5
    accel_profile = adaptive

    touchpad {
        natural_scroll = true
        drag_lock = true
}
}

# =========================
# LAYOUT
# =========================
dwindle {
    #pseudotile = yes
    #preserve_split = yes
}

# =========================
# AUTOSTART
# =========================

source = ~/.config/hypr/autostart.conf

# =========================
# WINDOW RULES
# =========================

source = ~/.config/hypr/windowrules.conf

# =========================
# KEYBINDS
# =========================

source = ~/.config/hypr/keybinds.conf
