# =========================
# GENERAL
# =========================
general {
    layout = dwindle
    gaps_in = 5
    gaps_out = 10
    border_size = 2

}

scrolling {
    direction = right
    column_width = 0.9
    fullscreen_on_one_column = true
    follow_focus = true
    focus_fit_method = 1
}
# =========================
# DECORATION
# =========================
decoration {
    rounding = 9

    blur {
        enabled = yes
        size = 10
        passes = 3
        ignore_opacity = yes
        contrast = 1.1
    }

    shadow {
        enabled = no
    }
}

# =========================
# ANIMATIONS
# =========================
animations {
    enabled = yes

    bezier = fast, 0.25, 0.9, 0.3, 1.0

    animation = windows, 1, 5, fast
    animation = windowsOut, 1, 5, fast
    animation = border, 1, 4, default
    animation = fade, 1, 5, default
    animation = workspaces, 1, 5, fast
}
