# =========================
# WINDOW RULES
# =========================
windowrule = opacity 0.8 0.8, match:class thunar

windowrule = float 1, match:class ^(com.gabm.satty)$
windowrule = size 800 500, match:class ^(com.gabm.satty)$
windowrule = center 1, match:class ^(com.gabm.satty)$

windowrule = opacity 0.8 0.8, match:title ^(Wall-Picker)$
windowrule = match:title ^(Wall-Picker)$
windowrule = match:title ^(Wall-Picker)$


windowrule = float 1, match:class org.pulseaudio.pavucontrol
windowrule = size 800 500, match:class org.pulseaudio.pavucontrol
windowrule = center 1, match:class org.pulseaudio.pavucontrol

windowrule = float 1, match:class blueman-manager
windowrule = size 800 500, match:class blueman-manager
windowrule = center 1, match:class blueman-manager

layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 1, match:namespace rofi-wayland

windowrule = float 1, match:class com.github.hluk.copyq
windowrule = size 800 500, match:class com.github.hluk.copyq
windowrule = center 1, match:class com.github.hluk.copyq

windowrule = float 1, match:class ^(vlc)$
windowrule = size 1000 700, match:class ^(vlc)$
windowrule = center 1, match:class ^(vlc)$
windowrule = opaque 1, match:class ^(vlc)$
windowrule = dim_around 1, match:class ^(vlc)$

#windowrule = float 1, match:class ^(kitty)$
#windowrule = size 1000 700, match:class ^(kitty)$
#windowrule = center 1, match:class ^(kitty)$

windowrule = float 1, match:class ^(mpv)$
windowrule = size 1000 700, match:class ^(mpv)$
windowrule = center 1, match:class ^(mpv)$
windowrule = opaque 1, match:class ^(mpv)$
windowrule = dim_around 1, match:class ^(mpv)$

windowrule = float 1, match:class ^(org.kde.gwenview)$
windowrule = size 1000 700, match:class ^(org.kde.gwenview)$
windowrule = center 1, match:class ^(org.kde.gwenview)$
windowrule = opaque 1, match:class ^(org.kde.gwenview)$
windowrule = dim_around 1, match:class ^(org.kde.gwenview)$
