foreground            #e2c5d9
background            #1a0a1c

selection_foreground  #1a0a1c
selection_background  #ff007f

color0  #1a0a1c
color1  #ff0055
color2  #00f0b5
color3  #f3e03b
color4  #00bfff
color5  #ff007f
color6  #00f0ff
color7  #e2c5d9
color8  #36193b
color9  #ff3377
color10 #33ffcc
color11 #f5e663
color12 #33ccff
color13 #ff3399
color14 #33f3ff
color15 #ffd6f3

cursor                #ff007f
cursor_text_color     #1a0a1c
url_color             #00f0ff

cursor_trail 4
cursor_trail_decay 0.1 0.4
