# =========================
# GENERAL
# =========================
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2

    col.active_border = rgba(d3d3d3ff)
    col.inactive_border = rgba(44475aaa)
}

# =========================
# DECORATION
# =========================
decoration {
    rounding = 8

    blur {
        enabled = yes
        size = 10
        passes = 3
        ignore_opacity = yes
        contrast = 1.1
    }

    shadow {
        enabled = no
    }
}

# =========================
# ANIMATIONS
# =========================
animations {
    enabled = yes

    bezier = fast, 0.25, 0.9, 0.3, 1.0

    animation = windows, 1, 5, fast
    animation = windowsOut, 1, 5, fast
    animation = border, 1, 4, default
    animation = fade, 1, 5, default
    animation = workspaces, 1, 5, fast
}